# Generated by Django 4.2.2 on 2024-08-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronavip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculosvip',
            options={'ordering': ['order'], 'verbose_name': 'Vehiculo VIP', 'verbose_name_plural': 'Vehiculos VIP'},
        ),
    ]
