# Generated by Django 4.2.2 on 2024-09-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronavip', '0002_alter_vehiculosvip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculosvip',
            name='image',
            field=models.ImageField(default='null', upload_to='vehiculos_vip', verbose_name='Imagen'),
        ),
    ]
