# Generated by Django 4.2.1 on 2023-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserver',
            name='user',
        ),
        migrations.AlterField(
            model_name='reserver',
            name='hour',
            field=models.CharField(max_length=50, verbose_name='Hora'),
        ),
    ]
