# Generated by Django 4.2.1 on 2023-06-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_remove_reserver_user_alter_reserver_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='ve_name',
            field=models.CharField(default='null', max_length=300, verbose_name='Nombre del Vehiculo'),
        ),
        migrations.AddField(
            model_name='reserver',
            name='ve_value',
            field=models.CharField(default='null', max_length=300, verbose_name='Valor del Vehiculo'),
        ),
    ]
