# Generated by Django 4.2.1 on 2023-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='zone',
            name='hotel',
            field=models.ManyToManyField(blank=True, null=True, to='reserve.hotellist', verbose_name='Hoteles'),
        ),
    ]
