# Generated by Django 4.2.1 on 2023-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_rename_crated_at_zone_created_at_zone_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='value_tour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor de viaje'),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='ve_value',
            field=models.CharField(default='null', max_length=300, verbose_name='Valor del viaje'),
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='value_tour',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='value_tour',
            field=models.ManyToManyField(blank=True, null=True, to='reserve.zone', verbose_name='Valor de viaje'),
        ),
    ]
