# Generated by Django 4.2.1 on 2023-06-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_zone_value_tour_alter_reserver_ve_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellist',
            name='zona_ind',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='value_tour',
            field=models.ManyToManyField(to='reserve.zone', verbose_name='Valor de viaje'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='hotel',
            field=models.ManyToManyField(to='reserve.hotellist', verbose_name='Hoteles'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='value_tour',
            field=models.CharField(max_length=100, verbose_name='Valor de viaje'),
        ),
    ]
