# Generated by Django 4.2.1 on 2023-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_hotellist_zona_ind_alter_vehiculos_value_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellist',
            name='zona_ind',
        ),
        migrations.AddField(
            model_name='hotellist',
            name='price1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valor de Van estandar'),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='price2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valor de Auto estandar'),
        ),
    ]
