# Generated by Django 4.2.1 on 2023-06-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserve', '0009_airportorterminal_price1_airportorterminal_price2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='value_tour',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('value', models.CharField(max_length=300, verbose_name='Valor')),
                ('price1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Valor de Auto estandar')),
                ('price2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Valor de Van estandar')),
                ('address_URL', models.URLField(max_length=400, verbose_name='URL a Google Maps')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Aeropuerto/Terminal',
                'verbose_name_plural': 'Aeropuertos/Terminales',
                'ordering': ['order'],
            },
        ),
    ]
