# Generated by Django 4.2.2 on 2023-07-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_remove_vehiculos_value_tour_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
    ]
