# Generated by Django 4.2.2 on 2023-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_alter_destination_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado el'),
        ),
    ]
