# Generated by Django 4.2.2 on 2023-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_zone_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.RemoveField(
            model_name='zone',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='value_tour',
        ),
        migrations.AddField(
            model_name='zone',
            name='Barrio',
            field=models.ManyToManyField(to='reserve.barriolist', verbose_name='Hoteles'),
        ),
    ]
