# Generated by Django 4.2.2 on 2023-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_barriolist_remove_zone_hotel_remove_zone_value_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='Barrio',
        ),
        migrations.AddField(
            model_name='zone',
            name='barrios',
            field=models.ManyToManyField(to='reserve.barriolist', verbose_name='Barrios'),
        ),
    ]
