# Generated by Django 4.2.2 on 2023-07-15 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_remove_zone_barrios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='zone',
        ),
        migrations.AddField(
            model_name='destination',
            name='barrio',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Barrio'),
            preserve_default=False,
        ),
    ]
