# Generated by Django 4.2.2 on 2024-08-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_vehiculos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'ordering': ['order'], 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
