# Generated by Django 4.2.2 on 2023-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
        ),
        migrations.RemoveField(
            model_name='tours',
            name='include',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='noinclude',
        ),
        migrations.AddField(
            model_name='tours',
            name='include',
            field=models.ManyToManyField(blank=True, to='tours.inclusiones', verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='tours',
            name='noinclude',
            field=models.ManyToManyField(blank=True, to='tours.exclusiones', verbose_name='No Incluye'),
        ),
    ]
