# Generated by Django 4.2.2 on 2023-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_exclusiones_inclusiones_remove_tours_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valor'),
        ),
    ]
