# Generated by Django 4.2.2 on 2023-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tours_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
    ]
