# Generated by Django 4.2.2 on 2023-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tours_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='cash',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
    ]
