# Generated by Django 4.2.2 on 2024-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_air_booking_nair'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default='2024-01-01', verbose_name='Checkin'),
        ),
    ]
