# Generated by Django 4.2.2 on 2024-12-26 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destino',
            field=models.CharField(default='null', max_length=200, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origen',
            field=models.CharField(default='null', max_length=200, verbose_name='Origen'),
        ),
    ]
