# Generated by Django 4.2.2 on 2024-12-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_destino_booking_hora_booking_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='opcion',
            field=models.CharField(default='null', max_length=100, verbose_name='Opcion'),
        ),
    ]
