# Generated by Django 4.2.2 on 2025-01-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_opcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=0, verbose_name='Checkin'),
        ),
    ]
