# Generated by Django 4.2.2 on 2025-01-14 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_ret',
            field=models.DateField(default=0, verbose_name='Fecha de retorno'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destino_ret',
            field=models.CharField(default='Null', max_length=200, verbose_name='Destino de retorno'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hora_ret',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de retorno '),
        ),
        migrations.AddField(
            model_name='booking',
            name='origen_ret',
            field=models.CharField(default='null', max_length=200, verbose_name='Origen de retorno'),
        ),
    ]
