# Generated by Django 4.2.2 on 2025-02-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_booking_city_remove_booking_contry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='childre',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
