# Generated by Django 4.2.2 on 2025-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_childre_remove_booking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hora_ret',
            field=models.TimeField(default=0, verbose_name='Hora de retorno '),
        ),
    ]
