# Generated by Django 4.2.2 on 2025-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_hora_ret'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recorrido',
            field=models.CharField(default='null', max_length=100, verbose_name='Recorrido'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hora_ret',
            field=models.TimeField(default=0, verbose_name='Hora de retorno'),
        ),
    ]
